# TCL File Generated by Component Editor 21.1
# Fri Jul 08 17:42:22 PDT 2022
# DO NOT MODIFY


# 
# display_scanout "display_scanout" v21.1
#  2022.07.08.17:42:22
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module display_scanout
# 
set_module_property DESCRIPTION ""
set_module_property NAME display_scanout
set_module_property VERSION 21.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME display_scanout
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL display_scanout
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file display_scanout.sv SYSTEM_VERILOG PATH display_scanout.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk in_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset in_reset_n reset_n Input 1


# 
# connection point ltm_r
# 
add_interface ltm_r conduit end
set_interface_property ltm_r associatedClock clk
set_interface_property ltm_r associatedReset ""
set_interface_property ltm_r ENABLED true
set_interface_property ltm_r EXPORT_OF ""
set_interface_property ltm_r PORT_NAME_MAP ""
set_interface_property ltm_r CMSIS_SVD_VARIABLES ""
set_interface_property ltm_r SVD_ADDRESS_GROUP ""

add_interface_port ltm_r ltm_r new_signal Output 8


# 
# connection point ltm_g
# 
add_interface ltm_g conduit end
set_interface_property ltm_g associatedClock clk
set_interface_property ltm_g associatedReset ""
set_interface_property ltm_g ENABLED true
set_interface_property ltm_g EXPORT_OF ""
set_interface_property ltm_g PORT_NAME_MAP ""
set_interface_property ltm_g CMSIS_SVD_VARIABLES ""
set_interface_property ltm_g SVD_ADDRESS_GROUP ""

add_interface_port ltm_g ltm_g new_signal Output 8


# 
# connection point ltm_b
# 
add_interface ltm_b conduit end
set_interface_property ltm_b associatedClock clk
set_interface_property ltm_b associatedReset ""
set_interface_property ltm_b ENABLED true
set_interface_property ltm_b EXPORT_OF ""
set_interface_property ltm_b PORT_NAME_MAP ""
set_interface_property ltm_b CMSIS_SVD_VARIABLES ""
set_interface_property ltm_b SVD_ADDRESS_GROUP ""

add_interface_port ltm_b ltm_b new_signal Output 8


# 
# connection point ltm_hd
# 
add_interface ltm_hd conduit end
set_interface_property ltm_hd associatedClock clk
set_interface_property ltm_hd associatedReset ""
set_interface_property ltm_hd ENABLED true
set_interface_property ltm_hd EXPORT_OF ""
set_interface_property ltm_hd PORT_NAME_MAP ""
set_interface_property ltm_hd CMSIS_SVD_VARIABLES ""
set_interface_property ltm_hd SVD_ADDRESS_GROUP ""

add_interface_port ltm_hd ltm_hd new_signal Output 1


# 
# connection point ltm_vd
# 
add_interface ltm_vd conduit end
set_interface_property ltm_vd associatedClock clk
set_interface_property ltm_vd associatedReset ""
set_interface_property ltm_vd ENABLED true
set_interface_property ltm_vd EXPORT_OF ""
set_interface_property ltm_vd PORT_NAME_MAP ""
set_interface_property ltm_vd CMSIS_SVD_VARIABLES ""
set_interface_property ltm_vd SVD_ADDRESS_GROUP ""

add_interface_port ltm_vd ltm_vd new_signal Output 1


# 
# connection point ltm_den
# 
add_interface ltm_den conduit end
set_interface_property ltm_den associatedClock clk
set_interface_property ltm_den associatedReset ""
set_interface_property ltm_den ENABLED true
set_interface_property ltm_den EXPORT_OF ""
set_interface_property ltm_den PORT_NAME_MAP ""
set_interface_property ltm_den CMSIS_SVD_VARIABLES ""
set_interface_property ltm_den SVD_ADDRESS_GROUP ""

add_interface_port ltm_den ltm_den new_signal Output 1


# 
# connection point pixel
# 
add_interface pixel avalon_streaming end
set_interface_property pixel associatedClock clk
set_interface_property pixel associatedReset reset
set_interface_property pixel dataBitsPerSymbol 24
set_interface_property pixel errorDescriptor ""
set_interface_property pixel firstSymbolInHighOrderBits true
set_interface_property pixel maxChannel 0
set_interface_property pixel readyLatency 0
set_interface_property pixel ENABLED true
set_interface_property pixel EXPORT_OF ""
set_interface_property pixel PORT_NAME_MAP ""
set_interface_property pixel CMSIS_SVD_VARIABLES ""
set_interface_property pixel SVD_ADDRESS_GROUP ""

add_interface_port pixel in_pixel_data data Input 24
add_interface_port pixel in_pixel_valid valid Input 1
add_interface_port pixel in_pixel_ready ready Output 1


# 
# connection point next_frame
# 
add_interface next_frame conduit end
set_interface_property next_frame associatedClock clk
set_interface_property next_frame associatedReset ""
set_interface_property next_frame ENABLED true
set_interface_property next_frame EXPORT_OF ""
set_interface_property next_frame PORT_NAME_MAP ""
set_interface_property next_frame CMSIS_SVD_VARIABLES ""
set_interface_property next_frame SVD_ADDRESS_GROUP ""

add_interface_port next_frame out_next_frame next_frame Output 1

