# TCL File Generated by Component Editor 21.1
# Sat Jul 09 14:09:41 PDT 2022
# DO NOT MODIFY


# 
# flag_sync "flag_sync" v21.1
#  2022.07.09.14:09:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module flag_sync
# 
set_module_property DESCRIPTION ""
set_module_property NAME flag_sync
set_module_property VERSION 21.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME flag_sync
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL flag_sync
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file flag_sync.sv SYSTEM_VERILOG PATH flag_sync.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point in
# 
add_interface in conduit end
set_interface_property in associatedClock clk_in
set_interface_property in associatedReset ""
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in in_flag next_frame Input 1


# 
# connection point out
# 
add_interface out conduit end
set_interface_property out associatedClock clk_out
set_interface_property out associatedReset ""
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_flag next_frame Output 1


# 
# connection point clk_in
# 
add_interface clk_in clock end
set_interface_property clk_in clockRate 0
set_interface_property clk_in ENABLED true
set_interface_property clk_in EXPORT_OF ""
set_interface_property clk_in PORT_NAME_MAP ""
set_interface_property clk_in CMSIS_SVD_VARIABLES ""
set_interface_property clk_in SVD_ADDRESS_GROUP ""

add_interface_port clk_in clk_in clk Input 1


# 
# connection point clk_out
# 
add_interface clk_out clock end
set_interface_property clk_out clockRate 0
set_interface_property clk_out ENABLED true
set_interface_property clk_out EXPORT_OF ""
set_interface_property clk_out PORT_NAME_MAP ""
set_interface_property clk_out CMSIS_SVD_VARIABLES ""
set_interface_property clk_out SVD_ADDRESS_GROUP ""

add_interface_port clk_out clk_out clk Input 1

