# TCL File Generated by Component Editor 21.1
# Sat Jul 09 14:11:04 PDT 2022
# DO NOT MODIFY


# 
# pixel_reader "pixel_reader" v21.1
#  2022.07.09.14:11:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pixel_reader
# 
set_module_property DESCRIPTION ""
set_module_property NAME pixel_reader
set_module_property VERSION 21.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pixel_reader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pixel_reader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file pixel_reader.sv SYSTEM_VERILOG PATH pixel_reader.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point pixel
# 
add_interface pixel avalon_streaming start
set_interface_property pixel associatedClock clk
set_interface_property pixel associatedReset reset
set_interface_property pixel dataBitsPerSymbol 24
set_interface_property pixel errorDescriptor ""
set_interface_property pixel firstSymbolInHighOrderBits true
set_interface_property pixel maxChannel 0
set_interface_property pixel readyLatency 0
set_interface_property pixel ENABLED true
set_interface_property pixel EXPORT_OF ""
set_interface_property pixel PORT_NAME_MAP ""
set_interface_property pixel CMSIS_SVD_VARIABLES ""
set_interface_property pixel SVD_ADDRESS_GROUP ""

add_interface_port pixel st_pixel_data data Output 24
add_interface_port pixel st_pixel_ready ready Input 1
add_interface_port pixel st_pixel_valid valid Output 1


# 
# connection point next_frame
# 
add_interface next_frame conduit end
set_interface_property next_frame associatedClock clk
set_interface_property next_frame associatedReset ""
set_interface_property next_frame ENABLED true
set_interface_property next_frame EXPORT_OF ""
set_interface_property next_frame PORT_NAME_MAP ""
set_interface_property next_frame CMSIS_SVD_VARIABLES ""
set_interface_property next_frame SVD_ADDRESS_GROUP ""

add_interface_port next_frame next_frame next_frame Input 1


# 
# connection point mm
# 
add_interface mm avalon start
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clk
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm doStreamReads false
set_interface_property mm doStreamWrites false
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Output 20
add_interface_port mm mm_read read Output 1
add_interface_port mm mm_readdata readdata Input 16
add_interface_port mm mm_waitrequest waitrequest Input 1

